### ISSUE TITLE
Can it be used in Azure Web Apps?

### ISSUE THREAD

**Issue by jkatsiotis** [JonPSmith/Net.DistributedFileStoreCache#1]
Hello,

Can I use this cache in a multi-instance Azure web app?

**Comment by JonPSmith** [comment]
Yes, it will. That's how I plan to use it.

PS. Just to be very clear if you have a single web app that where you use Azure scale-out approach (i.e. multiple instances of the same app all running on the same web server) it just works. If you use a web farms, where some web instances are running on separate geographical servers, then it will still work but you need to do a bit more to define a common file directory for the cache file.

**Comment by jkatsiotis** [comment]
Thanks for the swift response. That's my setup, Web App that scales-out to multiple instances. One follow-up question: How are you handling the resetting of files on an instance that was restarted? Web apps might restart randomly (due to updates etc) and everything is being wiped clean and restored from the latest deploy.

**Comment by JonPSmith** [comment]
Hi @jkatsiotis,

> How are you handling the resetting of files on an instance that was restarted?

Generally a distributed cache shouldn't change when you deploy new software or your app restarts and the FileStore distributed cache follows that approach. That's because other instances will be using the distributed cache. When you run / restart an app where FileStore cache registered in it will look for an existing FileStore cache json file and uses that. If this the first time this app has been run the FileStore cache register code will create an empty FileStore cache json file for you.

If you really want to reset the FileStore cache on startup you can by using its FileStore cache `ClearAll` method, but I don't recommend that. 

PS. Make sure you read [this section](https://github.com/JonPSmith/Net.DistributedFileStoreCache/wiki/Deployment-and-testing-%22gocha's%22#making-sure-your-production-filestore-cache-isnt-overwritten-on-deployment) of the docs on what to do to ensure a deployment doesn't overwrite your production FileStore cache.

**Comment by jkatsiotis** [comment]
I wasn't talking about deployments but for unplanned restarts by the platform, because I was thinking my own setup. For future reference if you have WEBSITE_LOCAL_CACHE_OPTION=Always (like I do) this lib probably will not work. 

If anyone is interested can find more about it [here](https://www.how2code.info/en/blog/website_dynamic_cache-and-website_local_cache_option/).

> Azure App Service Local Cache
[Azure App Service Local Cache](https://docs.microsoft.com/en-us/azure/app-service/overview-local-cache) improves performance and web app uptime by copying your files to local storage. It does so by introducing a local cache on each web app instance.

>
>More exactly:
When you web app starts, it copies the files from central Azure Storage to your local cache.
The local cache handles reads and writes, but the writes are never sent to the central Azure Storage.
When you restart your app, it will discard the local cache and reread the files from the central Azure Storage.
When publishing changes (for example from Visual Studio), they don't become visible to your apps until restarted.
This gives you much better file read/write performance for your website. It also means you get fewer restarts due to Azure Storage Share changes (but you need to restart after publishing your app).

>
>Local Cache is useful if your website doesn't need to store any files permanently. In other cases, like Wordpress, enabling Local Cache is not a good idea.

**Comment by JonPSmith** [comment]
Hi @jkatsiotis,

That's interesting. So, what you have written you create a separate cache for each instance of your application. If that is correct, then you don't have a distributed cache, but a per-instance cache. Is that right?

I expect you were interested in the `Get` speed of the FileStore distributed cache, but if you have a per-instance cache couldn't use an Memory cache in your app? It should be very quick like my FileStore cache.

I built the FileStore cache to be distributed because I have data that I want a `Set` from one instance can be seen by all the instances. I also want that data to be durable too, which is the normal approach on Azure App service.

PS. I don't think you need the FileStore cache, but I _think_ it will work in WEBSITE_LOCAL_CACHE_OPTION=Always. I say that because you could have FileStore cache in each cache, and the FileStore cache file would be destroyed when the app stops and when the app starts the FileStore cache would create a empty FileStore cache file.
