### ISSUE TITLE
Fails after about 10 entries

### ISSUE THREAD

**Issue by alelom** [JonPSmith/Net.DistributedFileStoreCache#3]
I started using this in my project, and initial testing went well. Then, I realised that only few values were stored in the cache. 

I then created the following test (NUnit) to verify whether the `IDistributedFileStoreCacheClass` was working fine:

```cs

namespace Caching
{
    public class CachingTests
    {
        IDistributedFileStoreCacheClass fileCache;

        [OneTimeSetUp]
        public void FileCacheSetup()
        {
            var services = new ServiceCollection();

            //services.AddTransient<IMatchRepository, MatchRepositoryStub>(); // another example of adding service

            services.AddDistributedFileStoreCache(options =>
            {
                options.WhichVersion = FileStoreCacheVersions.Class;
                options.SecondPartOfCacheFileName = "CachingTests";
                options.PathToCacheFileDirectory = @"C:\temp";
            });

            var serviceProvider = services.BuildServiceProvider();

            fileCache = serviceProvider.GetService<IDistributedFileStoreCacheClass>();

            fileCache.ShouldNotBeNull();
        }

        [TestCase(1)]
        [TestCase(5)]
        [TestCase(10)]
        [TestCase(20)]
        [TestCase(50)]
        [TestCase(100)]
        [TestCase(500)]
        [TestCase(1000)]
        [TestCase(10000)]
        public void FileCacheTest_ManyEntries(int length)
        {
            List<string> keys = new();
            Random random = new Random(0);
            for (int i = 0; i < length; i++)
            {
                var data = AutoBogus.AutoFaker.Generate<NominatimData>();
                string key = $"{random.Next()}";
                keys.Add(key);
                fileCache.SetClass(key, data);
            }

            foreach (var key in keys)
            {
                var fromCache = fileCache.GetClass<NominatimData>(key);
                fromCache.ShouldNotBeNull();
            }
        }
    }
}
```

This passes for the first `TestCase` values (until 10, inclusive) but for higher numbers it fails on `fromCache.ShouldNotBeNull()`. The values are not written to the file anymore after about 10 values.

**Comment by JonPSmith** [comment]
Hi @alelom,

I think your problem is you don't clear the cache every time you run a test. This means the cache will just filled up, especially because registering of the file cache doesn't clear the cache (that's done on purpose). This means once you have run the test once, then later runs the cache is most likely full. Yoe can do this via the i.e. `fileCache.ClearAll()` method, I do this in most of my tests - see [this example](https://github.com/JonPSmith/Net.DistributedFileStoreCache/blob/main/Test/UnitTests/TestDistributedFileStoreCacheClass.cs).

The second issue is you haven't set the size of the cache. In the [FileStore cache article](https://www.thereformedprogrammer.net/a-net-distributed-cache-with-a-25-nanosecond-read-time/) and in the [documentation](https://github.com/JonPSmith/Net.DistributedFileStoreCache/wiki) that there is a trade-off between the size of the cache and the time it takes to add another entry (see [performance figures](https://github.com/JonPSmith/Net.DistributedFileStoreCache/blob/main/README.md#performance-figures)).

I don't know how big each of your cache entries is, but I suspect that you might need to set the `MaxBytesInJsonCacheFile` option to a bigger size (default is 10,000 bytes). Read the [Tips on making your cache fast](https://github.com/JonPSmith/Net.DistributedFileStoreCache/wiki/Tips-on-making-your-cache-fast) document for a details on how calculate the correct size for your project.

**Comment by alelom** [comment]
Thank you, the size of the cache and its clearing must be the causes of this. Feel free to close!
